[env]
TERM = "xterm-256color"

[shell]
program = "zellij"

[window]
padding.x = 16
padding.y = 14
decorations = "none"
opacity = 0.97

[window.dimensions]
columns = 145
lines = 42

[keyboard]
bindings = [
{ key = "F11", action = "ToggleFullscreen" }
]
